/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouseui;

import javax.swing.JLabel;
import javax.swing.JTextField;
import manager.manageProduct;
import receiver.receiveOrder;

/**
 *
 * @author Xianming
 */
public class ReceiverUI extends javax.swing.JPanel
{
    private JLabel jLabel9;
    private JTextField locationTextField;

    /**
     * Creates new form ReceiverUI
     */
    public ReceiverUI()
    {
        newOrder = new receiveOrder();
        initComponents();
    }

    ReceiverUI(int i) {
        newOrder = new receiveOrder();
        newProduct = new manageProduct();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        orderNumberTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        priceTextField = new javax.swing.JTextField();
        sizeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();  // for location
        descriptionTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        locationTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        

        //setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);


        jLabel1.setText("Name");

        jLabel2.setText("Item Number");

        jLabel3.setText("Quantity");

        jLabel4.setText("Category");

        jLabel5.setText("Price");

        jLabel6.setText("Size");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(newOrder.getCategoryList()));

        jLabel7.setText("Description");

        jLabel8.setText("Weight");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                confirmReceive(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancel(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                 .addContainerGap()
                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                      //    .add(jScrollPane1)
                      .add(layout.createSequentialGroup()
                           .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                     .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                          .add(jLabel2)
                                          .add(jLabel3)
                                          .add(jLabel1))
                                     .add(18, 18, 18)
                                     .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                          .add(layout.createSequentialGroup()
                                               .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                               .add(18, 18, 18)
                                               .add(jLabel4))
                                          .add(layout.createSequentialGroup()
                                               .add(orderNumberTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                               .add(18, 18, 18)
                                               .add(jLabel5))
                                          .add(layout.createSequentialGroup()
                                               .add(quantityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                               .add(18, 18, 18)
                                               .add(jLabel6)))
                                     .add(18, 18, 18)
                                     .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                          .add(sizeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                          .add(layout.createSequentialGroup()
                                               .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                       .add(layout.createSequentialGroup()
                                                               .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                               .add(18, 18, 18)
                                                               .add(jLabel7))
                                                       .add(layout.createSequentialGroup()
                                                               .add(priceTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                               .add(18, 18, 18)
                                                               .add(jLabel8)))
                                               .add(18, 18, 18)
                                               .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                       .add(weightTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                       .add(descriptionTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                                .add(layout.createSequentialGroup()
                                     .add(jButton1)
                                     .add(18, 18, 18)
                                     .add(jButton2)))
                           .add(0, 0, Short.MAX_VALUE)))
                 .addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                 .addContainerGap()
                 //      .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                 .add(18, 18, 18)
                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                      .add(jLabel1)
                      .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                      .add(jLabel4)
                      .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                      .add(jLabel7)
                      .add(descriptionTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                 .add(18, 18, 18)
                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                      .add(jLabel2)
                      .add(orderNumberTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                      .add(jLabel5)
                      .add(priceTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                      .add(jLabel8)
                      .add(weightTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                 .add(12, 12, 12)
                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                      .add(jLabel3)
                      .add(quantityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                      .add(jLabel6)
                      .add(sizeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                 .add(18, 18, 18)
                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                      .add(jButton1)
                      .add(jButton2))
                 .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        nameTextField.getAccessibleContext().setAccessibleName("");
        add(locationTextField);
        //pack();
    }// </editor-fold>

    private void confirmReceive(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
        if (nameTextField.getText().compareTo("") != 0
                && quantityTextField.getText().compareTo("") != 0
                && priceTextField.getText().compareTo("") != 0
                && sizeTextField.getText().compareTo("") != 0
                && descriptionTextField.getText().compareTo("") != 0
                && weightTextField.getText().compareTo("") != 0)
        {
            if(this.function ==0){
                 newOrder.setItemName(nameTextField.getText());
                newOrder.setItemQuantity(Integer.valueOf(quantityTextField.getText()));
                newOrder.setPrice(Float.valueOf(priceTextField.getText()));
                newOrder.setSize(Float.valueOf(sizeTextField.getText()));
                newOrder.setDescription(descriptionTextField.getText());
                newOrder.setItemCategory(jComboBox1.getSelectedIndex()+1);
                newOrder.setWeight(Float.valueOf(weightTextField.getText()));
                newOrder.createOrder();

            // Check if order number is empty.
            // If user input order number, add the product into exist order
            // If order number is not empty, create a new order


                 int newOrderNumber = -1;
                if (orderNumberTextField.getText().compareTo("") != 0)
                {
                     newOrder.setOrderID(Integer.valueOf(orderNumberTextField.getText()));
                    newOrder.addItemsToOrder();
                 }
                 else
                {
                     newOrderNumber = newOrder.addProduct();
                 }


                nameTextField.setText("");
                quantityTextField.setText("");
                priceTextField.setText("");
                 sizeTextField.setText("");
                descriptionTextField.setText("");
                weightTextField.setText("");

                if (newOrderNumber != -1)
                {
                    orderNumberTextField.setText(String.valueOf(newOrderNumber));
                }

           } // end if function =0
            
//            if(this.function ==1){
//                newProduct
//            } //end if function =1
            
        }
    }

    private void cancel(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ReceiverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ReceiverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ReceiverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ReceiverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ReceiverUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField orderNumberTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JTextField weightTextField;
    private receiveOrder newOrder;
    private int function = 0;  // function for UI. 0 for receiver, 1 for add product list,2 for edit product 
    private manageProduct newProduct;
    // End of variables declaration
}
