/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouseui;

import shipper.makeShipment;


/**
 *
 * @author Xianming
 */
public class ShippingUI extends javax.swing.JFrame {

    /**
     * Creates new form ShippingUI
     */
    public ShippingUI() {
        newShipment = new makeShipment();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        
        shipmentTitle = new String[]{"Number", "Name", "Quantity", "Destination", "Date"};

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jButton1.setText("Future Plan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFuturePlanPopup(evt);
            }
        });

        jButton2.setText("Ship");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openShippingPopup(evt);
            }
        });
        //modify by Xingze
        //First parameter of setModel returns from makeShipment
        jTable1.setModel(new javax.swing.table.DefaultTableModel((Object[][]) newShipment.shipRequire(),shipmentTitle));

        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .addContainerGap(199, Short.MAX_VALUE))
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void openFuturePlanPopup(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        FuturePlanPopup futurePopup = new FuturePlanPopup();
        futurePopup.setVisible(true);
    }                                    

    private void openShippingPopup(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        int choosenItem = jTable1.getSelectedRow();
        
        //if do not choose an shipment, ship button is not available
        if(choosenItem != -1){
            ShippingConfirmPopup shippingPopup = new ShippingConfirmPopup(newShipment);
            setShipmentInfo(choosenItem);
            shippingPopup.setVisible(true);
        }
    }                                  
/**
 * @author Xingze Guo
 * @param choosen from UI
 */
    private void setShipmentInfo(int choosen){
        newShipment.inputItemInfor((Integer)jTable1.getValueAt(choosen, 0), (String)jTable1.getValueAt(choosen, 1), (Integer)jTable1.getValueAt(choosen, 2),
                                    (String)jTable1.getValueAt(choosen, 3),(Integer)jTable1.getValueAt(choosen, 4));
    }
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private Object shipmentInfo[][];
    private String shipmentTitle[];
    private makeShipment newShipment;
    // End of variables declaration                   
}
